name: Build and Release SGL-Kernel-NPU

on:
  release:
    types:
      - published

  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build_and_release.yml'
      - 'config.ini'

jobs:

  build-and-release:
    runs-on: ubuntu-24.04-arm
    container:
      image: quay.io/ascend/cann:8.3.rc2-a3-ubuntu22.04-py3.11
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Mark repository safe
        run: |
          git config --system --add safe.directory ${GITHUB_WORKSPACE}

      - name: Install dependency
        run: |
          bash scripts/npu_ci_install_dependency.sh

      - name: Build SGL-Kernel-NPU
        run: |
          env -i PATH=${PATH} bash --login -c "
            export LD_LIBRARY_PATH=${ASCEND_HOME_PATH}/runtime/lib64/stub:${LD_LIBRARY_PATH} && \
            ./build.sh -a kernels
          "

      - name: Build Torch-Memory-Saver
        run: |
          env -i PATH=${PATH} bash --login -c "
            export LD_LIBRARY_PATH=${ASCEND_HOME_PATH}/runtime/lib64/stub:${LD_LIBRARY_PATH} && \
            ./build.sh -a memory-saver
          "

      - name: Build DeepEP
        run: |
          env -i PATH=${PATH} bash --login -c "
            export LD_LIBRARY_PATH=${ASCEND_HOME_PATH}/runtime/lib64/stub:${LD_LIBRARY_PATH} && \
            ./build.sh -a deepep
          "
          ls -al output/

      - name: Upload Release Artifacts
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: output/*.whl
