name: Release_test

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/release_test.yml"
      - "scripts/release_ci_dependency.sh"
  workflow_dispatch:
jobs:
  build-and-upload:
    runs-on: ubuntu-22.04-arm
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.3.rc1-a3-ubuntu22.04-py3.11
    steps:
      - name: Clean git config
        run: |
          CONFIG_KEY='http.https://gh-proxy.test.osinfra.cn/.extraheader'
          git config --global --unset "$CONFIG_KEY" || true

      - name: Clean workspace
        run: |
          sudo rm -rf --one-file-system "$GITHUB_WORKSPACE"/* "$GITHUB_WORKSPACE"/.* 2>/dev/null || true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Install dependencies
        run: |
          CACHING_URL="cache-service.nginx-pypi-cache.svc.cluster.local"
          sed -Ei "s@(ports|archive).ubuntu.com@${CACHING_URL}:8081@g" /etc/apt/sources.list
          pip config set global.index-url http://${CACHING_URL}/pypi/simple
          pip config set global.trusted-host ${CACHING_URL}
          bash scripts/release_ci_dependency.sh    

      - name: Build wheel packages
        run: bash build.sh

