name: Release

on:
  release:
    types:
      - published
      - prereleased

jobs:
  build-and-upload:
    permissions:
      contents: write
    runs-on: ubuntu-22.04-arm
    container:
      image: quay.io/ascend/cann:8.3.rc2-a3-ubuntu22.04-py3.11

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Build packages
        run: |
          env -i PATH=${PATH} bash --login scripts/release_ci_dependency.sh

      - name: Upload packages to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
